include: package:flutter_lints/flutter.yaml

linter:
  rules:
    always_use_package_imports: true
    prefer_single_quotes: true
    avoid_dynamic_calls: true
    no_leading_underscores_for_local_identifiers: true
    prefer_const_constructors: true
    prefer_final_locals: true
    unawaited_futures: true
    cancel_subscriptions: true
    prefer_relative_imports: false

analyzer:
  language:
    strict-casts: true
    strict-inference: true
    strict-raw-types: true
  exclude:
    - build/**
    - lib/**.g.dart
    - lib/**.freezed.dart
 
